### ISSUE TITLE
Label  `Administrator` anjlok

### ISSUE THREAD

**Issue by hyuzea** [OpenSID/tema-labs#4]
![image](https://user-images.githubusercontent.com/3823496/64346569-8f19b880-d01c-11e9-9c0b-0f5edaf3812b.png)

**Comment by hyuzea** [comment]
Atau memang gayanya begitu ya?

**Comment by labkoding-id** [comment]
sudah ada update terbaru silahkan ganti bung ,itu sudah di perbaiki bung

**Comment by labkoding-id** [comment]
![screencapture-localhost-opensid-index-php-first-2019-09-05-15_54_58](https://user-images.githubusercontent.com/54000006/64353364-8c579d00-cff5-11e9-8818-b8c26e1ff59b.png)
